### ISSUE TITLE
Code line number?

### ISSUE THREAD

**Issue by zehuichen123** [HoverBaum/meilidu-hexo#12]
![image](https://user-images.githubusercontent.com/24351120/52388335-deb8f580-2ac8-11e9-8099-65ceffcdc042.png)

**Comment by HoverBaum** [comment]
That is a bug 🙂 

As a work around you can hide the line number by adding `display: none` the the `.gutter pre` in highlight.styl https://github.com/HoverBaum/meilidu-hexo/blob/master/source/css/highlight.styl#L79

That should of cause be temporary, while we find and solve the underlying issue here.

Pull Requests are also welcome.

**Comment by zehuichen123** [comment]
👌Thanks for your suggestion~

**Comment by HoverBaum** [comment]
The issue is fixed now. You can see it working again on my blog https://hoverbaum.net/2019/01/29/Automate-click-through-testing-with-Puppeteer/
